- name: reload transmission
  systemd:
    name: transmission-daemon
    daemon_reload: yes
    state: restarted

- name: test nginx and restart
  command: nginx -t
  notify: Restart nginx

- name: Restart nginx
  systemd:
    name: nginx
    state: restarted

- name: save iptables
  shell: "iptables-save > /etc/iptables/rules.v4"

- name: restart openpyn
  systemd:
    name: openpyn
    state: restarted

- name: reload jackett
  systemd:
    name: jackett
    daemon_reload: yes
    state: restarted

- name: reload flexget
  systemd:
    name: flexget.timer
    daemon_reload: yes
    state: restarted

- name: reload telegram-bot
  systemd:
    name: telegram-bot
    daemon_reload: yes
    state: restarted
