---
- name: restart nginx
  systemd:
    name: nginx
    state: restarted

- name: save iptables
  shell: "iptables-save > /etc/iptables/rules.v4"

- name: restart torrent-cage
  systemd:
    name: torrent-cage
    daemon_reload: true
    state: restarted

- name: restart transmission
  systemd:
    name: transmission-daemon
    daemon_reload: true
    state: restarted
  listen: 'restart torrent-cage'

- name: restart wg-quick
  systemd:
    name: wg-quick@wg0
    daemon_reload: true
    state: restarted
  listen: 'restart wg-quick'

- name: restart jackett
  systemd:
    name: jackett
    daemon_reload: true
    state: restarted
  listen: 'restart torrent-cage'

- name: restart flexget
  systemd:
    name: flexget
    daemon_reload: true
    state: restarted
  listen: 'restart torrent-cage'

- name: restart telegram-bot
  systemd:
    name: telegram-bot
    daemon_reload: true
    state: restarted
