---
- name: Save iptables
  ansible.builtin.shell: "iptables-save > /etc/iptables/rules.v4"

- name: Restart torrent-cage
  ansible.builtin.systemd:
    name: torrent-cage
    daemon_reload: true
    state: restarted

- name: Restart transmission
  ansible.builtin.systemd:
    name: transmission-daemon
    daemon_reload: true
    state: restarted
  listen: 'Restart torrent-cage'

- name: Restart wg-quick
  ansible.builtin.systemd:
    name: wg-quick@wg0
    daemon_reload: true
    state: restarted

- name: Restart jackett
  ansible.builtin.systemd:
    name: jackett
    daemon_reload: true
    state: restarted
  listen: 'Restart torrent-cage'

- name: Restart flexget
  ansible.builtin.systemd:
    name: flexget
    daemon_reload: true
    state: restarted
  listen: 'Restart torrent-cage'

- name: Restart telegram-bot
  ansible.builtin.systemd:
    name: telegram-bot
    daemon_reload: true
    state: restarted
