- name: Create TV directory
  become: yes
  become_user: torrent
  file:
    path: /home/torrent/media/torrent/TV
    state: directory
    mode: '0755'

- name: Create Movie directory
  become: yes
  become_user: torrent
  file:
    path: /home/torrent/media/torrent/Movies
    state: directory
    mode: '0755'

- name: Create temp TV directory
  become: yes
  become_user: torrent
  file:
    path: /home/torrent/media/temp/TV
    state: directory
    mode: '0755'

- name: Create temp Movies directory
  become: yes
  become_user: torrent
  file:
    path: /home/torrent/media/temp/Movies
    state: directory
    mode: '0755'

- name: Install required pip libraries
  pip:
    name:
      - flexget==v3.1.102
      - python-telegram-bot
      - transmission-rpc
      - pysftp
      # https://github.com/Flexget/Flexget/issues/2749
      - pytz==2020.5

- name: Create flexget directory
  become: yes
  become_user: torrent
  file:
    path: /home/torrent/flexget
    state: directory
    mode: '0755'

- name: Copy flexget config file
  become: yes
  become_user: torrent
  copy:
    src: flexget-config.yml
    dest: /home/torrent/flexget/config.yml
    mode: '0644'

- name: Copy flexget vars file
  become: yes
  become_user: torrent
  template:
    src: flexget-vars.yml.j2
    dest: /home/torrent/flexget/vars.yml
    mode: '0644'
  no_log: true

- name: Copy flexget timer file
  copy:
    src: flexget.timer
    dest: /lib/systemd/system/flexget.timer
    mode: '0644'
  notify:
    - reload flexget

- name: Copy flexget service file
  copy:
    src: flexget.service
    dest: /lib/systemd/system/flexget.service
    mode: '0644'
  notify:
    - reload flexget

- name: Ensure flexget timer is started/enabled
  become: yes
  systemd:
    name: flexget.timer
    enabled: yes
    state: started

- name: Install openssh
  apt:
    update_cache: yes
    name: ssh

- name: Create default ssh directories
  become: yes
  become_user: torrent
  file:
    path: '/home/torrent/.ssh'
    state: 'directory'
    mode: '0755'

- name: Generate SSH keys
  become: yes
  become_user: torrent
  command: ssh-keygen -b 2048 -t rsa -f /home/torrent/.ssh/id_rsa -q -N ""
  args:
    creates: /home/torrent/.ssh/id_rsa

- name: Display resolv.conf contents
  command: cat /home/torrent/.ssh/id_rsa.pub
  register: command_output
  tags: ['never', 'print_ssh']

- name: Print to console
  debug: msg="SSH Public key is:\n{{command_output.stdout}}"
  tags: ['never', 'print_ssh']

- name: Copy telegram-bot binary (x86)
  copy:
    src: ../bot/torrent-bot_x86
    dest: /usr/bin/telegram-bot
    mode: '0755'
  when: "'x86_64' in ansible_architecture and torrent_telegram_token is defined"
  notify: 'reload telegram-bot'

- name: Copy telegram-bot binary (arm)
  copy:
    src: ../bot/torrent-bot_arm
    dest: /usr/bin/telegram-bot
    mode: '0755'
  when: "'arm' in ansible_architecture and torrent_telegram_token is defined"
  notify: 'reload telegram-bot'

- name: Copy telegram-bot service file
  template:
    src: telegram-bot.service.j2
    dest: /lib/systemd/system/telegram-bot.service
    mode: '0644'
  notify: 'reload telegram-bot'
  no_log: true
  when: 'torrent_telegram_token is defined'

- name: Ensure telegram-bot is started/enabled
  become: yes
  systemd:
    name: telegram-bot
    enabled: yes
    state: started
  when: 'torrent_telegram_token is defined'
