---
- name: Install packages
  apt:
    update_cache: true
    name:
      - libffi-dev

- name: Create TV directory
  become: true
  become_user: torrent
  file:
    path: /home/torrent/media/torrent/TV
    state: directory
    mode: '0755'

- name: Create Movie directory
  become: true
  become_user: torrent
  file:
    path: /home/torrent/media/torrent/Movies
    state: directory
    mode: '0755'

- name: Create TV directory
  become: true
  become_user: torrent
  file:
    path: /home/torrent/media/TV
    state: directory
    mode: '0755'

- name: Create Movies directory
  become: true
  become_user: torrent
  file:
    path: /home/torrent/media/Movies
    state: directory
    mode: '0755'

- name: Install required pip libraries
  pip:
    name:
      - "flexget=={{ torrent_flexget_version }}"
      - python-telegram-bot
      - transmission-rpc
      # https://github.com/Flexget/Flexget/issues/2749
      - "pytz=={{ torrent_pytz_version }}"

- name: Create flexget directory
  become: true
  become_user: torrent
  file:
    path: /home/torrent/flexget
    state: directory
    mode: '0755'

- name: Copy flexget config file
  become: true
  become_user: torrent
  copy:
    src: flexget-config.yml
    dest: /home/torrent/flexget/config.yml
    mode: '0644'
  notify:
    - restart flexget

- name: Copy flexget vars file
  become: true
  become_user: torrent
  template:
    src: flexget-vars.yml.j2
    dest: /home/torrent/flexget/vars.yml
    mode: '0644'
  no_log: true
  notify:
    - restart flexget

- name: Copy flexget service file
  template:
    src: flexget.service.j2
    dest: /lib/systemd/system/flexget.service
    mode: '0644'
  notify:
    - restart flexget

- name: Ensure flexget is started/enabled
  become: true
  systemd:
    name: flexget
    enabled: true
    state: started
