---
- name: Create Torrent TV directory
  ansible.builtin.file:
    path: /home/torrent/torrents/TV
    state: directory
    mode: '0755'

- name: Create Torrent TV directory
  ansible.builtin.file:
    path: /home/torrent/torrents/Movies
    state: directory
    mode: '0755'

- name: Create TV directory
  ansible.builtin.file:
    path: /home/torrent/media/TV
    state: directory
    mode: '0755'

- name: Create Movies directory
  ansible.builtin.file:
    path: /home/torrent/media/Movies
    state: directory
    mode: '0755'

- name: Create flexget directory
  ansible.builtin.file:
    path: /home/torrent/flexget/config
    state: directory
    mode: '0755'

- name: Copy flexget config file
  ansible.builtin.copy:
    src: flexget-config.yml
    dest: /home/torrent/flexget/config/config.yml
    mode: '0644'

- name: Copy subtitle extractor file
  ansible.builtin.copy:
    src: extract-subtitles.sh
    dest: /home/torrent/flexget/config/extract-subtitles.sh
    mode: '0644'

- name: Copy flexget vars file
  ansible.builtin.template:
    src: flexget-vars.yml.j2
    dest: /home/torrent/flexget/config/vars.yml
    mode: '0644'
  no_log: true
