---
# https://github.com/dotnet/runtime/issues/7764
# Alternative would be to use mono for these cases, but it's very bloated
- name: Use mono form armv6
  ansible.builtin.set_fact:
    use_mono: true
  when: "'armv6l' in ansible_machine or torrent_jackett_use_mono"

- name: Use .net for the rest
  ansible.builtin.set_fact:
    use_mono: false
  when: "'armv6l' not in ansible_machine and not torrent_jackett_use_mono"

- name: Include mono
  ansible.builtin.include_tasks: jackett/dotnet.yml
  when: not use_mono

- name: Include dotnet jackett
  ansible.builtin.include_tasks: jackett/mono.yml
  when: use_mono

- name: Enable jackett service
  ansible.builtin.systemd:
    name: jackett
    enabled: true
    state: started

- name: Install caddy ingress
  ansible.builtin.import_role:
    name: caddy
    tasks_from: subdomains
  vars:
    subdomain_name: jackett
    subdomain_host: "{{ torrent_cage_torrent_ip }}"
    subdomain_port: 9117
    state: present
