---
- name: Include boilerplate
  ansible.builtin.include_tasks: boilerplate.yml
  tags: torrent-boilerplate

- name: Include iptables and network namespace
  ansible.builtin.include_tasks: torrent-cage.yml
  tags: torrent-cage

- name: Include transmission
  ansible.builtin.include_tasks: transmission.yml
  tags: transmission

- name: Include wireguard
  ansible.builtin.include_tasks: wireguard.yml
  when: "torrent_vpn_disabled is false and torrent_cage_non_enforcing is false"
  tags:
    - wireguard
    - notest

- name: Include jackett
  ansible.builtin.include_tasks: jackett.yml
  tags: jackett

- name: Include flexget
  ansible.builtin.include_tasks: flexget.yml
  tags: flexget

- name: Include telegram-bot
  ansible.builtin.include_tasks: telegram-bot.yml
  tags: telegram-bot
  when: torrent_telegram_token is defined

- name: Manual task to include telegram token in Flexget database
  ansible.builtin.include_tasks: telegram-flexget-fix.yml
  when: add_telegram_to_flexget | default(False)
  tags:
    - never
    - telegram-flexget-fix
    - wireguard
    # - notest
