---
- name: Include boilerplate
  include: boilerplate.yml
  tags: torrent-boilerplate

- name: Include iptables and network namespace
  include: torrent-cage.yml
  tags: torrent-cage

- name: Include nginx server
  include: nginx.yml
  tags: nginx

- name: Include transmission
  include: transmission.yml
  tags: transmission

- name: Include openpyn
  include: openpyn.yml
  when: "torrent_openpyn_disabled is false and torrent_cage_non_enforcing is false"
  tags:
    - openpyn
    - notest

- name: Include jackett
  include: jackett.yml
  tags: jackett

- name: Include flexget
  include: flexget.yml
  tags: flexget

- name: Include telegram-bot
  include: telegram-bot.yml
  tags: telegram-bot

- name: Manual task to include telegram token in Flexget database
  include: telegram-flexget-fix.yml
  when: add_telegram_to_flexget | default(False)
  tags:
    - never
    - telegram-flexget-fix
