---
- name: Create torrent user
  ansible.builtin.include_role:
    name: compose
    tasks_from: create-user
  vars:
    user: torrent

- name: Add vpn group
  ansible.builtin.group:
    name: vpn
    state: present
    gid: "{{ torrent_user_gid_owner }}"

- name: Include flexget bootstrap
  when: torrent_enable_flexget | default(False)
  ansible.builtin.include_tasks: flexget.yml

- name: Create Radaar directory
  ansible.builtin.file:
    path: /home/torrent/radarr
    state: directory
    owner: torrent
    mode: '0755'

- name: Create Sonaar directory
  ansible.builtin.file:
    path: /home/torrent/sonarr
    state: directory
    owner: torrent
    mode: '0755'

- name: Include compose role
  ansible.builtin.include_role:
    name: compose
  vars:
    service_name: torrent
    user: torrent
    backup:
      enabled: true
      directories:
        - /home/torrent/flexget/config
        - /home/torrent/jackett
        - /home/torrent/transmission/config
        - /home/torrent/radarr
        - /home/torrent/sonarr
      schedule: "0 5 * * *"
    tailscale:
      enabled: "{{ torrent_tailscale_enabled }}"
      hostname: "{{ torrent_tailscale_hostname }}"
      tag: "{{ torrent_tailscale_tag }}"
      exit_node: "{{ torrent_tailscale_exit_node }}"
      mounts:
        - /home/torrent/media:/media

# - name: Manual task to include telegram token in Flexget database
#   ansible.builtin.include_tasks: telegram-flexget-fix.yml
#   when: torrent_enable_telegram_bot
#   tags:
#     - never
#     - telegram-flexget-fix
