- name: Include boilerplate
  include: boilerplate.yml

- name: Include nginx server
  include: nginx.yml

- name: Include transmission
  include: transmission.yml

- name: Include openpyn
  include: openpyn.yml

- name: Include jackett
  include: jackett.yml

- name: Include flexget
  include: flexget.yml
