---
- name: Create torrent user
  ansible.builtin.include_role:
    name: compose
    tasks_from: create-user
  vars:
    user: torrent

- name: Add vpn group
  ansible.builtin.group:
    name: vpn
    state: present
    gid: "{{ torrent_user_gid_owner }}"

- name: Include flexget bootstrap
  ansible.builtin.include_tasks: flexget.yml

- name: Include compose role
  ansible.builtin.include_role:
    name: compose
  vars:
    service_name: torrent
    user: torrent
    run_as_root: true
    run_in_docker: true

- name: Add transmission ingress
  ansible.builtin.include_role:
    name: caddy
    tasks_from: subdomains
  vars:
    subdomain_name: torrents
    subdomain_host: 127.0.0.1
    subdomain_port: 9091
    state: present
    auth_user: "{{ torrent_transmission_user }}"
    auth_password: "{{ torrent_transmission_password }}"

- name: Add jacket ingress
  ansible.builtin.include_role:
    name: caddy
    tasks_from: subdomains
  vars:
    subdomain_name: jackett
    subdomain_host: 127.0.0.1
    subdomain_port: 9117
    state: present
