---
- name: Create torrent user
  ansible.builtin.include_role:
    name: compose
    tasks_from: create-user
  vars:
    user: torrent

- name: Create media directories
  ansible.builtin.file:
    path: "/home/torrent/media/{{ item }}"
    state: directory
    owner: torrent
    mode: '0755'
  loop:
    - torrents/TV
    - torrents/Movies
    - TV
    - Movies

- name: Copy subtitle extractor file
  ansible.builtin.copy:
    src: extract-subtitles.sh
    dest: /home/torrent/media/extract-subtitles.sh
    owner: torrent
    mode: '0755'
  notify: "Restart torrent - local"

- name: Include compose role
  ansible.builtin.include_role:
    name: compose
  vars:
    service_name: torrent
    user: torrent
    backup:
      enabled: true
      directories:
        - /home/torrent/jackett
        - /home/torrent/transmission/config
        - /home/torrent/radarr
        - /home/torrent/sonarr
      schedule: "0 5 * * *"
    tailscale:
      enabled: "{{ torrent_tailscale_enabled }}"
      hostname: "{{ torrent_tailscale_hostname }}"
      tag: "{{ torrent_tailscale_tag }}"
      exit_node: "{{ torrent_tailscale_exit_node }}"
      mounts:
        - /home/torrent/media:/media
