---
- name: Create torrent user
  ansible.builtin.include_role:
    name: compose
    tasks_from: create-user
  vars:
    user: torrent

- name: Add vpn group
  ansible.builtin.group:
    name: vpn
    state: present
    gid: "{{ torrent_user_gid_owner }}"

- name: Include flexget bootstrap
  ansible.builtin.include_tasks: flexget.yml

- name: Include compose role
  ansible.builtin.include_role:
    name: compose
  vars:
    service_name: torrent
    user: torrent
    tailscale:
      enabled: "{{ torrent_tailscale_enabled }}"
      hostname: "{{ torrent_tailscale_hostname }}"
      tag: "{{ torrent_tailscale_tag }}"
      exit_node: "{{ torrent_tailscale_exit_node }}"
      mounts:
        - /home/torrent/media:/media

- name: Manual task to include telegram token in Flexget database
  ansible.builtin.include_tasks: telegram-flexget-fix.yml
  when: add_telegram_to_flexget | default(False)
  tags:
    - never
    - telegram-flexget-fix

- name: Run backup role
  ansible.builtin.include_role:
    name: restic
    tasks_from: backup
  vars:
    restic_backup_name: torrents
    restic_backup_args: "/home/torrent/flexget/config /home/torrent/jackett /home/torrent/transmission/config"
    restic_forget_args: "--keep-last 2"
    restic_schedule: "*-*-* 5:00:00"
