- name: Create server wireguard keys directory
  become: true
  become_user: torrent
  ansible.builtin.file:
    path: '/home/torrent/wireguard/server'
    state: directory
    mode: '0755'

- name: Create peer wireguard keys directory
  become: true
  become_user: torrent
  ansible.builtin.file:
    path: '/home/torrent/wireguard/peer1'
    state: directory
    mode: '0755'

- name: Save private key server
  become: true
  become_user: torrent
  ansible.builtin.copy:
    content: "{{ torrent_custom_vpn_server_private_key }}"
    dest: /home/torrent/wireguard/server/privatekey-server
    mode: '0644'

- name: Save public key server
  become: true
  become_user: torrent
  ansible.builtin.copy:
    content: "{{ torrent_custom_vpn_server_public_key }}"
    dest: /home/torrent/wireguard/server/publickey-server
    mode: '0644'

- name: Save private key peer
  become: true
  become_user: torrent
  ansible.builtin.copy:
    content: "{{ torrent_custom_vpn_client_private_key }}"
    dest: /home/torrent/wireguard/peer1/privatekey-peer1
    mode: '0644'

- name: Save public key peer
  become: true
  become_user: torrent
  ansible.builtin.copy:
    content: "{{ torrent_custom_vpn_client_public_key }}"
    dest: /home/torrent/wireguard/peer1/publickey-peer1
    mode: '0644'

- name: Save preshared key
  become: true
  become_user: torrent
  ansible.builtin.copy:
    content: "{{ torrent_custom_vpn_preshared_key }}"
    dest: /home/torrent/wireguard/peer1/presharedkey-peer1
    mode: '0644'
