---
- name: Create default nginx directories
  ansible.builtin.file:
    path: '/etc/nginx/ssl'
    state: 'directory'
    mode: '0755'

- name: Install nginx
  ansible.builtin.apt:
    update_cache: true
    name: ['nginx', 'openssl']

- name: Generate self signed SSL certificates
  ansible.builtin.command: >
    openssl req
      -new
      -newkey rsa:4096
      -days 365
      -nodes
      -x509
      -subj "/C=DE/ST=HH/L=HH/O=rpi/CN=rpi"
      -keyout /etc/nginx/ssl/transmission.key
      -out /etc/nginx/ssl/transmission.pem
  args:
    creates: '/etc/nginx/ssl/transmission.pem'
  notify: Restart nginx

- name: Generate X bit dhparam.pem file
  ansible.builtin.command: openssl dhparam -dsaparam -out /etc/nginx/ssl/dhparam.pem 2048
  args:
    creates: '/etc/nginx/ssl/dhparam.pem'
  notify: Restart nginx

- name: Install python package to use htpasswd
  ansible.builtin.pip:
    name: passlib

- name: Enable/Start nginx service
  ansible.builtin.systemd:
    name: nginx
    enabled: true
    state: started
