- name: Create nginx directories
  file:
    path: /etc/nginx/sites-enabled
    state: directory
    mode: '0755'

- name: Create default nginx directories
  file:
    path: '{{ item }}'
    state: 'directory'
    mode: '0755'
  with_items:
    - '/etc/nginx/sites-available'
    - '/etc/nginx/sites-enabled'
    - '/etc/nginx/ssl'

- name: Install nginx
  pacman:
    update_cache: yes
    name: ['nginx', 'openssl']

- name: Insert sites-enabled conf
  lineinfile:
    dest: /etc/nginx/nginx.conf
    regexp: "^include /etc/nginx/sites-enabled/*.conf;"
    insertbefore: "server {"
    line: "include /etc/nginx/sites-enabled/*.conf;"

- name: Generate self signed SSL certificates
  command: >
    openssl req
      -new
      -newkey rsa:4096
      -days 365
      -nodes
      -x509
      -subj "/C=DE/ST=HH/L=HH/O=rpi/CN=rpi"
      -keyout /etc/nginx/ssl/transmission.key
      -out /etc/nginx/ssl/transmission.pem
  args:
    creates: '/etc/nginx/ssl/transmission.pem'
  notify: test nginx and restart

- name: Generate X bit dhparam.pem file
  command: openssl dhparam -out /etc/nginx/ssl/dhparam.pem 2048
  args:
    creates: '/etc/nginx/ssl/dhparam.pem'
  notify: test nginx and restart

- name: Install python package to use htpasswd
  pip:
    name: passlib

- name: Enable/Start nginx service
  systemd:
    name: nginx
    enabled: yes
    state: started
