- name: Install required packages
  apt:
    update_cache: yes
    name: ['unzip', 'wget', 'openvpn', 'iptables', 'iptables-persistent']

- name: Install required pip libraries
  pip:
    name: ['pexpect', 'openpyn==2.7.5']

- name: create openpyn service files
  expect:
    command: openpyn --init
    responses:
      username: "{{ torrent_nordvpn_user }}"
      password: "{{ torrent_nordvpn_password }}"
      systemd: "{{ torrent_nordvpn_country | default('de') }}"
    creates: /etc/systemd/system/openpyn.service
  # no_log: true
  notify: restart openpyn
  timeout: 300

- name: Start openpyn service
  systemd:
    name: openpyn
    enabled: yes
    state: started

- name: Allow torrent traffic from tun0
  iptables:
    out_interface: tun0
    chain: OUTPUT
    gid_owner: "{{ torrent_user_gid_owner }}"
    jump: ACCEPT
  notify: save iptables

- name: Allow torrent traffic from localhost
  iptables:
    out_interface: lo
    chain: OUTPUT
    gid_owner: "{{ torrent_user_gid_owner }}"
    jump: ACCEPT
  notify: save iptables

- name: Allow torrent traffic from localhost
  iptables:
    chain: OUTPUT
    gid_owner: "{{ torrent_user_gid_owner }}"
    jump: REJECT
    reject_with: icmp-port-unreachable
  notify: save iptables
