- name: Install required packages
  pacman:
    update_cache: yes
    name: ['unzip', 'which', 'wget', 'openvpn']

- name: Install required pip libraries
  pip:
    name: ['pexpect', 'openpyn==2.7.5']

- name: create openpyn service files
  expect:
    command: openpyn --init
    responses:
      # TODO: Secret variable
      username: guigui
      password: vixi
      systemd: de
    creates: /etc/systemd/system/openpyn.service
  # no_log: true
  notify: restart openpyn

- name: Start openpyn service
  systemd:
    name: openpyn
    enabled: yes
    state: started

- name: Allow torrent traffic from tun0
  iptables:
    out_interface: tun0
    chain: OUTPUT
    # TODO Add this as variable
    gid_owner: "1500"
    jump: ACCEPT
  notify: save iptables

- name: Allow torrent traffic from localhost
  iptables:
    out_interface: lo
    chain: OUTPUT
    # TODO Add this as variable
    gid_owner: "1500"
    jump: ACCEPT
  notify: save iptables

- name: Allow torrent traffic from localhost
  iptables:
    chain: OUTPUT
    # TODO Add this as variable
    gid_owner: "1500"
    jump: REJECT
    reject_with: icmp-port-unreachable
  notify: save iptables

- name: Enable iptables-restore service
  systemd:
    name: iptables
    enabled: yes
    state: started
