---
- name: Install required packages
  apt:
    update_cache: true
    name: ['unzip', 'wget', 'openvpn']

- name: Install required pip libraries
  pip:
    name: ['pexpect', "openpyn=={{ torrent_openpyn_version }}"]

# Debian Bullseye doesn't bring /sbin/init linked to systemd binary anymore
# But openpyn expects it
- name: Create symbolic link from
  file:
    src: /lib/systemd/systemd
    dest: /sbin/init
    state: link

- name: Create openpyn override directory
  file:
    path: /etc/systemd/system/openpyn.service.d
    state: directory
    mode: '0755'

- name: Override openpyn service
  template:
    src: openpyn-override.conf.j2
    dest: /etc/systemd/system/openpyn.service.d/openpyn-override.conf
    mode: '0644'
  notify: restart openpyn

- name: create openpyn service files
  expect:
    # Using DNS Server from Cloudflare
    command: openpyn --init
    responses:
      username: "{{ torrent_nordvpn_user }}"
      password: "{{ torrent_nordvpn_password }}"
      systemd: "{{ torrent_nordvpn_country }}"
    creates: /etc/systemd/system/openpyn.service
  notify: restart openpyn
  no_log: true
  timeout: 300

- name: Start openpyn service
  systemd:
    name: openpyn
    enabled: true
    state: started
