---
- name: Stop torrent service
  ansible.builtin.systemd:
    name: compose-torrent
    state: stopped

- name: Touch Matrix movie
  become: true
  become_user: torrent
  ansible.builtin.file:
    path: "/home/torrent/media/torrents/Movies/Matrix (1999).mkv"
    mode: "0644"
    state: touch

- name: Wait for user input
  ansible.builtin.pause:
    prompt: "Send a message to the chat like \"/search Movie\" before continuing"

- name: Run flexget
  community.docker.docker_container:
    image: docker.io/wiserain/flexget:latest
    name: flexget-fix-telegram
    entrypoint: "flexget"
    command: "execute --task move-movies"
    volumes:
      - /home/torrent/flexget/config:/config
      - /home/torrent/media/torrents:/downloads
      - /home/torrent/media:/media
  changed_when: false

- name: Start torrent service
  ansible.builtin.systemd:
    name: compose-torrent
    state: started

- name: Remove Matrix temp file
  ansible.builtin.file:
    path: "/home/torrent/media/Movies/The Matrix (1999)"
    state: absent
