---
- name: Install required packages
  community.general.pacman:
    update_cache: true
    name: ['iptables', 'procps', 'iproute2']

- name: Copy torrent-cage-up script file
  ansible.builtin.template:
    src: torrent-cage-up.sh.j2
    dest: /usr/bin/torrent-cage-up
    mode: '0755'
  notify: 'Restart torrent-cage'

- name: Copy torrent-cage-down script file
  ansible.builtin.template:
    src: torrent-cage-down.sh.j2
    dest: /usr/bin/torrent-cage-down
    mode: '0755'
  notify: 'Restart torrent-cage'

- name: Copy torrent-cage systemd service file
  ansible.builtin.copy:
    src: torrent-cage.service
    dest: /lib/systemd/system/torrent-cage.service
    mode: '0644'
  notify: 'Restart torrent-cage'

- name: Enable and start torrent-cage service
  ansible.builtin.systemd:
    name: torrent-cage
    enabled: true
    state: started

- name: Allow routing packets
  ansible.posix.sysctl:
    name: net.ipv4.ip_forward
    value: '1'
    sysctl_set: true

- name: Drop forward packets by default
  ansible.builtin.iptables:
    chain: FORWARD
    policy: DROP
  notify: Save iptables

- name: Apply NAT to packets coming from the network namespace
  ansible.builtin.iptables:
    table: nat
    chain: POSTROUTING
    source: "{{ torrent_cage_torrent_ip }}/24"
    jump: MASQUERADE
    out_interface: "{{ torrent_cage_main_interface }}"
  notify: Save iptables

- name: Accept packets to torrent virtual pair
  ansible.builtin.iptables:
    chain: FORWARD
    in_interface: "{{ torrent_cage_main_interface }}"
    out_interface: veth_host
    jump: ACCEPT
  notify: Save iptables

- name: Accept packets from torrent virtual pair
  ansible.builtin.iptables:
    chain: FORWARD
    in_interface: veth_host
    out_interface: "{{ torrent_cage_main_interface }}"
    jump: ACCEPT
  notify: Save iptables
