---
- name: Install transmission
  apt:
    update_cache: true
    name: transmission-daemon

- name: Create transmission override directory
  file:
    path: /etc/systemd/system/transmission-daemon.service.d
    state: directory
    mode: '0755'

- name: Copy transmission override systemd service
  template:
    src: transmission-override.conf.j2
    dest: /etc/systemd/system/transmission-daemon.service.d/transmission-override.conf
    mode: '0644'
  notify: restart transmission

- name: Enable/Start transmission service
  systemd:
    name: transmission-daemon
    daemon_reload: true
    enabled: true
    state: started

- name: Copy transmission nginx config file
  template:
    src: transmission.conf.j2
    dest: /etc/nginx/sites-available/torrent.conf
    mode: '0644'
  notify: restart nginx

- name: Symlink sites-available to sites-enabled
  file:
    src: '/etc/nginx/sites-available/torrent.conf'
    dest: '/etc/nginx/sites-enabled/torrent.conf'
    state: 'link'
  notify: restart nginx
