---
- name: Install transmission
  ansible.builtin.apt:
    update_cache: true
    name: transmission-daemon

- name: Create transmission override directory
  ansible.builtin.file:
    path: /etc/systemd/system/transmission-daemon.service.d
    state: directory
    mode: '0755'

- name: Copy transmission override systemd service
  ansible.builtin.template:
    src: transmission-override.conf.j2
    dest: /etc/systemd/system/transmission-daemon.service.d/transmission-override.conf
    mode: '0644'
  notify: Restart transmission

- name: Enable/Start transmission service
  ansible.builtin.systemd:
    name: transmission-daemon
    daemon_reload: true
    enabled: true
    state: started
