---
- name: Install required packages
  ansible.builtin.apt:
    update_cache: true
    name: ["wireguard", "resolvconf"]

- name: Enable wireguard module
  community.general.modprobe:
    name: wireguard
    state: present

- name: Save configuration to /etc/wireguard/wg0.conf
  ansible.builtin.copy:
    content: "{{ torrent_wireguard_configuration }}"
    dest: /etc/wireguard/wg0.conf
    mode: "0644"
  notify: "Restart wg-quick"

- name: Create wg-quick@ override directory
  ansible.builtin.file:
    path: '/etc/systemd/system/wg-quick@.service.d'
    state: 'directory'
    mode: '0755'

- name: Copy override file
  ansible.builtin.copy:
    src: wg-quick@.service
    dest: "/etc/systemd/system/wg-quick@.service.d/namespace.conf"
    mode: "0644"
  notify: "Restart wg-quick"

- name: Enable wg-quick service
  ansible.builtin.systemd:
    name: "wg-quick@wg0"
    enabled: true
    state: started
