#!/usr/bin/env python

# Script to move files from Google Takeout to a
# It takes the datewas from the accompanying JSON files

import os
import shutil
import json
from datetime import datetime
import sys

source_directory = sys.argv[1]
destination_directory = sys.argv[2]
move = sys.argv[3]


for root, dirs, files in os.walk(source_directory):
    for filename in files:
        if filename.endswith('.json'):
            with open(os.path.join(root, filename), 'r') as f:
                data = json.load(f)
                if 'photoTakenTime' not in data:
                    print("Skip " + filename)
                    continue

                file_name = data['title']

                timestamp = data['photoTakenTime']['timestamp']
                formatted_date = datetime.fromtimestamp(int(timestamp)).strftime('%Y/%m/')

            source_file = os.path.join(root, file_name)
            dest_path = os.path.join(destination_directory, formatted_date)
            destination_file = os.path.join(dest_path, file_name)

            if move == "true":
                print("Moving" + source_file + " to " + destination_file)
                os.makedirs(dest_path, exist_ok=True)
                try:
                    shutil.move(source_file, destination_file)
                except Exception as e:
                    print("Not moving: " + source_file)

            else:
                print("Would move " + source_file + " to " + destination_file)
