---
- name: Create directory for container volume
  file:
    path: "{{ item.host_path }}"
    state: directory
    owner: "{{ item.uid }}"
  with_items: "{{ share_container_volumes }}"

- name: Include compose role
  ansible.builtin.include_role:
    name: compose
  vars:
    service_name: share
    user: "{{ share_user }}"

- name: Add photoprism ingress
  ansible.builtin.include_role:
    name: caddy
    tasks_from: subdomains
  vars:
    subdomain_name: photos
    subdomain_host: 127.0.0.1
    subdomain_port: 2342
    state: present

- name: Include backup role
  ansible.builtin.include_role:
    name: restic
    tasks_from: backup
  vars:
    restic_backup_name: photos
    restic_backup_args: "/home/share/shares/pictures /home/share/photoprism/storage"
    restic_schedule: "*-*-* 2:00:00"

- name: Copy photoprism index service
  ansible.builtin.copy:
    src: photoprism-index.service
    dest: /etc/systemd/system/photoprism-index.service
    mode: '0644'

- name: Copy photoprism index timer
  ansible.builtin.copy:
    src: photoprism-index.timer
    dest: /etc/systemd/system/photoprism-index.timer
    mode: '0644'
  notify: "Restart photoprism-index"

- name: Enable index timer
  ansible.builtin.systemd:
    name: "photoprism-index.timer"
    state: started
    daemon_reload: true
    enabled: true


