---

- name: Create directory for container volume
  file:
    path: "{{ item.host_path }}"
    state: directory
    owner: "{{ item.uid }}"
  with_items: "{{ share_container_volumes }}"

- name: Include compose role
  ansible.builtin.include_role:
    name: compose
  vars:
    service_name: share
    user: "{{ share_user }}"
    # I had some issues with uid mapping on rootless podman and samba
    run_in_docker: true
    run_as_root: true

- name: Add photoprism ingress
  ansible.builtin.include_role:
    name: caddy
    tasks_from: subdomains
  vars:
    subdomain_name: photos
    subdomain_host: 127.0.0.1
    subdomain_port: 2342
    state: present

- name: Include backup role
  ansible.builtin.include_role:
    name: restic
    tasks_from: backup
  vars:
    restic_backup_name: photos
    restic_backup_args: "/home/syncthing/data"
    restic_schedule: "*-*-* 4:00:00"
