---
- name: Create directory for container volume
  file:
    path: "{{ item.host_path }}"
    state: directory
    owner: "{{ item.uid }}"
  with_items: "{{ share_container_volumes }}"

- name: Include compose role
  ansible.builtin.include_role:
    name: compose
  vars:
    service_name: share
    user: "{{ share_user }}"
    backup:
      enabled: true
      name: photos
      directories:
        - /home/share/shares/pictures
        - /home/share/photoprism/storage
      schedule: "0 3 * * *"
    tailscale:
      enabled: "{{ share_tailscale_enabled }}"
      hostname: "{{ share_tailscale_hostname }}"
      tag: "{{ share_tailscale_tag }}"
      # Put it in https, so photoprism can become a PWA
      https:
        "/": "http://localhost:2342"
      ports:
        # Share photos in the local network
        - 445:445
