# Copied scripts from https://github.com/T00mm/duckdns

- name: Copy timer file
  copy:
    src: duckdns.timer
    dest: /lib/systemd/system/duckdns.timer
    mode: '0644'
  notify:
    - reload services
    - restart duckdns

- name: Copy service file
  copy:
    src: duckdns.service
    dest: /lib/systemd/system/duckdns.service
    mode: '0644'
  notify:
    - reload services
    - restart duckdns

- name: Copy binary file
  copy:
    src: duckdns.sh
    dest: /usr/bin/duckdns
    mode: '0755'

- name: Ensures /etc/duckdns.d dir exists
  file:
    path: /etc/duckdns.d
    state: directory
    mode: '0755'

- name: Copy configuration file
  template:
    src: default.cfg.j2
    dest: /etc/duckdns.d/default.cfg
    mode: '0644'
