---
# Copied scripts from https://github.com/T00mm/duckdns
- name: Copy timer file
  ansible.builtin.copy:
    src: duckdns.timer
    dest: /lib/systemd/system/duckdns.timer
    mode: '0644'
  notify:
    - Restart duckdns

- name: Install packages
  ansible.builtin.apt:
    update_cache: true
    name: ['net-tools', 'curl']

- name: Copy duckdsn service file
  ansible.builtin.copy:
    src: duckdns.service
    dest: /lib/systemd/system/duckdns.service
    mode: '0644'
  notify:
    - Restart duckdns

- name: Copy binary file
  ansible.builtin.template:
    src: duckdns.sh.j2
    dest: /usr/bin/duckdns
    mode: '0755'

- name: Ensures /etc/duckdns.d dir exists
  ansible.builtin.file:
    path: /etc/duckdns.d
    state: directory
    mode: '0755'

- name: Copy configuration file
  ansible.builtin.template:
    src: default.cfg.j2
    dest: /etc/duckdns.d/default.cfg
    mode: '0644'
  no_log: true

- name: Ensure duckdns.timer is started/enabled
  ansible.builtin.systemd:
    name: duckdns.timer
    enabled: true
    state: started
