---
- name: Include compose role
  ansible.builtin.include_role:
    name: compose
  vars:
    service_name: paperless
    backup:
      enabled: true
      schedule: "0 2 * * *"
      directories:
        - /home/paperless/documents
    tailscale:
      enabled: "{{ paperless_tailscale_enabled }}"
      hostname: "{{ paperless_tailscale_hostname }}"
      tag: "{{ paperless_tailscale_tag }}"
      https:
        "/": "http://127.0.0.1:8000"
      mounts:
        - /home/paperless/documents:/documents
