---
- name: Include compose role
  ansible.builtin.include_role:
    name: compose
  vars:
    service_name: paperless
    user: paperless
    tailscale:
      enabled: "{{ paperless_tailscale_enabled }}"
      hostname: "{{ paperless_tailscale_hostname }}"
      tag: "{{ paperless_tailscale_tag }}"
      https:
        "/": "http://127.0.0.1:8000"
      mounts:
        - /home/paperless/documents:/documents

- name: Run backup role
  ansible.builtin.include_role:
    name: restic
    tasks_from: backup
  vars:
    restic_backup_name: paperless
    restic_backup_args: "/home/paperless/documents"
    restic_forget_args: "--keep-last 7"
    restic_schedule: "*-*-* 2:00:00"
