---
- name: Include compose role
  ansible.builtin.include_role:
    name: compose
  vars:
    service_name: cups
    user: cups

- name: Add caddy ingress
  ansible.builtin.include_role:
    name: caddy
    tasks_from: subdomains
  vars:
    subdomain_name: print
    subdomain_host: 127.0.0.1
    subdomain_port: 631
    state: present
    send_host_header: true

# - name: Run backup role
#   ansible.builtin.include_role:
#     name: restic
#     tasks_from: backup
#   vars:
#     restic_backup_name: syncthing
#     restic_backup_args: "/home/syncthing/data"
#     restic_forget_args: "--keep-last 7"
#     restic_schedule: "*-*-* 4:00:00"
