---
### REQUIRED

namespace: gjhenrique

name: rpi_stuff

version: 0.1.2

# The path to the Markdown (.md) readme file. This path is relative to the root of the collection
readme: README.md

authors:
  - Guilherme Henrique <gjhenrique@gmail.com>

description: Stuff to do with an old and retired raspberry pi

license_file: 'LICENSE'

tags:
  - raspberry
  - rpi
  - pi
  - torrent
  - transmission
  - jackett
  - flexget
  - jellyfin
  - nordvpn
  - duckdns
  - dynamicdns
  - syncthing

dependencies: {}

repository: https://github.com/gjhenrique/rpi_stuff
documentation: https://github.com/gjhenrique/rpi_stuff
homepage: https://github.com/gjhenrique/rpi_stuff
issues: https://github.com/gjhenrique/rpi_stuff/issues
