---
- name: Create user
  ansible.builtin.include_tasks: create-user.yml

- name: Include tailscale roles
  ansible.builtin.include_tasks: tailscale.yml
  when: tailscale.enabled == true

- name: Copy compose file
  ansible.builtin.template:
    # TODO: Maybe use lookup here?
    src: "{{ ansible_parent_role_paths[0] }}/templates/{{ compose_file_name }}"
    dest: "/home/{{ user }}/compose-{{ service_name }}.yml"
    mode: "0644"
    owner: "{{ user }}"
    group: "{{ user }}"
  notify: "Restart compose-{{ service_name }}"
  vars:
    user_id: "{{ user_facts.uid }}"

- name: Create systemd unit file
  ansible.builtin.template:
    src: compose.service.j2
    dest: "/etc/systemd/system/compose-{{ service_name }}.service"
    mode: "0644"
  notify: "Restart compose-{{ service_name }}"

- name: Enable and start compose service
  ansible.builtin.systemd:
    name: "compose-{{ service_name }}.service"
    state: started
    enabled: true
