---
- name: Get OAuth2 token
  ansible.builtin.uri:
    url: "https://login.tailscale.com/api/v2/oauth/token"
    method: POST
    body:
      client_id: "{{ tailscale_oauth_client }}"
      client_secret: "{{ tailscale_oauth_secret }}"
    body_format: form-urlencoded
    status_code: 200
    return_content: yes
  register: token_response

- name: Set access token
  set_fact:
    access_token: "{{ token_response.json.access_token }}"

- name: Create authkey
  ansible.builtin.uri:
    url: "https://api.tailscale.com/api/v2/tailnet/-/keys"
    method: POST
    user: "{{ access_token }}"
    force_basic_auth: true
    password: ""
    body_format: json
    body:
      capabilities:
        devices:
          create:
            reusable: true
            ephemeral: false
            preauthorized: true
            tags:
              - "{{ tailscale.tag }}"
      expiry_seconds: 0
    status_code: 200
    return_content: yes
  register: authkey_response

- name: Set auth key
  set_fact:
    authkey: "{{ authkey_response.json.key }}"

- name: Configure Tailscale HTTPS serve
  ansible.builtin.template:
    src: tailscale-serve.json.j2
    dest: /home/{{ user }}/tailscale-serve.json
    mode: '0644'
  when: tailscale.https is defined
  notify: "Restart compose-{{ service_name }}"

- name: Create compose file
  ansible.builtin.template:
    src: compose-tailscale.yml.j2
    dest: "/home/{{ user }}/compose-{{ service_name }}-tailscale.yml"
    mode: "0644"
    owner: "{{ user }}"
    group: "{{ user }}"
  vars:
    tailscale_authkey: "{{ authkey }}"
  notify: "Restart compose-{{ service_name }}"
