- name: set arm variable
  set_fact:
    jacket_arch: "ARM32"
  when: "'arm' in ansible_architecture"

- name: set x86 variable
  set_fact:
    jacket_arch: "AMDx64"
  when: "'x86_64' in ansible_architecture"

- name: Register current installed jacket version
  command: "/usr/lib/jackett/jackett --version"
  register: jackett_version
  changed_when: false
  ignore_errors: true

- name: New Jackett
  set_fact:
    install_jackett: true
  when: jackett_version.rc != 1 or (not jackett_version.stdout | regex_search(torrent_jackett_version))

- name: Download jackett bin
  get_url:
    url: "https://github.com/Jackett/Jackett/releases/download/{{ torrent_jackett_version }}/Jackett.Binaries.Linux{{ jacket_arch }}.tar.gz"
    dest: /tmp/jackett-dotnet-{{ torrent_jackett_version }}.tar.gz
  when: install_jackett is defined

- name: Extract jackett bin  # noqa 303
  shell: |
    tar -xzvf jackett-dotnet-{{ torrent_jackett_version }}.tar.gz
    rm -rf /usr/lib/jackett
    mv Jackett /usr/lib/jackett
  args:
    chdir: "/tmp"
  when: install_jackett is defined

- name: Deploy jackett service file
  copy:
    src: jackett-dotnet.service
    dest: /lib/systemd/system/jackett.service
    mode: '0644'
  notify:
    - reload jackett
