---
- name: Create caddy user
  ansible.builtin.include_role:
    name: compose
    tasks_from: create-user
  vars:
    user: caddy

- name: Create Caddyfile directory
  ansible.builtin.file:
    path: "/home/caddy/etc"
    state: directory
    mode: "0755"
    owner: "caddy"

- name: Create Caddyfile
  ansible.builtin.template:
    src: Caddyfile.j2
    dest: "/home/caddy/etc/Caddyfile"
    mode: "0644"
    owner: "caddy"

- name: Include compose role
  ansible.builtin.include_role:
    name: compose
  vars:
    service_name: caddy
    user: caddy
