---
- name: Create subdomains directory
  ansible.builtin.file:
    path: "/home/caddy/etc/subdomains"
    state: directory
    mode: "0755"
    owner: "caddy"

- name: Create subdomain file
  ansible.builtin.template:
    src: subdomain.caddy.j2
    dest: /home/caddy/etc/subdomains/{{ subdomain_name }}.caddy
    mode: "0644"
  notify: Restart caddy
  when: state == "present"

- name: Remove subdomain file
  ansible.builtin.file:
    path: /home/caddy/etc/subdomains/{{ subdomain_name }}.caddy
    state: absent
  notify: Restart caddy
  when: state == "absent"
