---
- name: Include compose role
  ansible.builtin.include_role:
    name: compose
  vars:
    service_name: actual
    backup:
      enabled: true
      schedule: "0 3 * * *"
      directories:
        - /home/actual/data
    tailscale:
      enabled: "{{ actual_tailscale_enabled }}"
      hostname: "{{ actual_tailscale_hostname }}"
      tag: "{{ actual_tailscale_tag }}"
      https:
        "/": "http://localhost:5006"
      mounts:
        - /home/actual/data:/data
