---

- name: Create caddy user
  ansible.builtin.include_role:
    name: compose
    tasks_from: create-user
  vars:
    user: nextcloud

- name: Create defaults directory
  ansible.builtin.file:
    path: /home/nextcloud/defaults
    state: directory
    owner: "nextcloud"
    mode: "0755"

- name: Copy config.php file
  ansible.builtin.template:
    src: "config.php.j2"
    dest: "/home/nextcloud/defaults/config.php"
    mode: "0644"
    owner: "nextcloud"
    group: "nextcloud"

- name: Include compose role
  ansible.builtin.include_role:
    name: compose
  vars:
    service_name: nextcloud
    user: "{{ nextcloud_user }}"

- name: Add caddy ingress
  ansible.builtin.include_role:
    name: caddy
    tasks_from: subdomains
  vars:
    subdomain_name: files
    subdomain_host: 127.0.0.1
    subdomain_port: 8081
    state: present
