---
- hosts: rpis
  become: true
  vars_files:
    - secrets.yml
    - vars.yml
  roles:
    - role: boilerplate
      tags: boilerplate
    - role: caddy
      tags: caddy
    - role: syncthing
      tags: syncthing
    - role: torrent
      tags: torrent
    - role: jellyfin
      tags: jellyfin
    - role: emby
      tags: emby
    - role: nextcloud
      tags: nextcloud
    - role: mount
      tags: mount
