---
- name: Sample app
  hosts: rpis
  become: true
  vars_files:
    - secrets.yml
    - vars.yml
  roles:
    - role: gjhenrique.rpi_stuff.syncthing
      tags: syncthing
      when: enable_syncthing is true
    - role: gjhenrique.rpi_stuff.torrent
      tags: torrent
      when: enable_torrent is true
    - role: gjhenrique.rpi_stuff.jellyfin
      tags: jellyfin
      when: enable_jellyfin is true
    - role: gjhenrique.rpi_stuff.mount
      tags: mount
      when: enable_mount is true
