---
- hosts: rpis
  become: true
  vars_files:
    - secrets.yml
    - vars.yml
  roles:
    - role: boilerplate
      tags: boilerplate
    - role: syncthing
      tags: syncthing
    - role: torrent
      tags: torrent
    - role: jellyfin
      tags: jellyfin
    - role: emby
      tags: emby
    - role: share
      tags: share
    - role: paperless
      tags: paperless
    - role: netdata
      tags: netdata
    - role: mount
      tags: mount

