---
- name: restart mounts
  systemd:
    name: "{{ file_systemd }}.mount"
    daemon_reload: true
    state: restarted
  vars:
    file_systemd: "{{ item.mount_path[1:].split('/') | join('-') }}"
  loop: "{{ mount_paths }}"
