---
- name: Fail when mount_path has spaces
  ansible.builtin.fail:
    msg: "This role doesn't support mount points with spaces. Tried to mount {{ item.mount_path }}"
  when: "' ' in item.mount_path"
  loop: "{{ mount_paths }}"

- name: Create systemd mount files for mountpoints
  ansible.builtin.template:
    src: file.mount.j2
    dest: "/lib/systemd/system/{{ file_systemd }}.mount"
    mode: "0644"
  vars:
    mount_path: "{{ item.mount_path }}"
    file_systemd: "{{ item.mount_path[1:].split('/') | join('-') }}"
    mount_from: "{{ item.mount_from }}"
    type: "{{ item.type }}"
    depends: "{{ item.depends | default(None) }}"
    options: "{{ item.options | default(None) }}"
  loop: "{{ mount_paths }}"
  notify: "Restart mounts"

- name: Start and enable mount points
  ansible.builtin.systemd:
    name: "{{ file_systemd }}.mount"
    enabled: true
    state: started
  vars:
    file_systemd: "{{ item.mount_path[1:].split('/') | join('-') }}"
  loop: "{{ mount_paths }}"

- name: Change ownership to specified user
  ansible.builtin.file:
    path: "{{ item.mount_path }}"
    owner: "{{ item.user }}"
    recurse: true
  when: "item.user is defined"
  loop: "{{ mount_paths }}"
