---
galaxy_info:
  author: your name
  description: Installs prometheus-node-exporter as a standalone systemd service
  license: license (GPL-2.0-or-later, MIT, etc)

  min_ansible_version: 2.1

  galaxy_tags: []

dependencies: []
