---
variables: vars.yml

templates:
  torrent:
    transmission:
      host: "{? transmission.ip ?}"
      port: 9091
      ratio: 1
      path: "{{ torrent_path }}"
      username: "{? transmission.username ?}"
      password: "{? transmission.password ?}"
      main_file_only: true
  notification:
    notify:
      entries:
        message: "{{ notification_message }}"
        via:
          - telegram:
              bot_token: "{? telegram.token ?}"
              parse_mode: html
              disable_previews: false
              recipients:
                - group: "{? telegram.group_name ?}"
  rename-serie-name:
    set:
      trakt_series_name: "{{ trakt_series_name | replace('&', 'and') | replace(':', '')}}"

tasks:
  download-rss:
    priority: 1
    rss: "{? rss.tv_url ?}"
    all_series: true
    trakt_lookup: true
    set:
      torrent_path: "{? torrent.torrent_tv_path ?}"
      notification_message: "🧲: {{ trakt_series_name }} - s{{ trakt_season|pad(2) }}e{{ trakt_episode | pad(2) }}"
    template:
      - torrent
      - notification

  move-series:
    priority: 2
    disable: [seen, seen_info_hash, retry_failed]
    filesystem:
      path: "{? torrent.torrent_tv_path ?}"
      recursive: true
      regexp: '.*\.(avi|mkv|mp4)$'
      retrieve: files
    accept_all: true
    trakt_lookup: true
    all_series:
      parse_only: true
    if:
      - trakt_series_name == None: reject
      - trakt_season == None: reject
    template:
      - notification
      - rename-serie-name
    set:
      notification_message: "✅: {{ trakt_series_name }} - s{{ trakt_season|pad(2) }}e{{ trakt_episode|pad(2) }}"
    move:
      to: "{? torrent.tv_path ?}/{{ trakt_series_name }}/s{{ trakt_season|pad(2) }}"
      rename: "{{ trakt_series_name }} - s{{ trakt_season|pad(2) }}e{{ trakt_episode|pad(2) }}"

  move-movies:
    priority: 3
    disable: [seen, seen_info_hash, retry_failed]
    regexp:
      from: title
      reject:
        - (s|d)ub(s|bed)
        - trailer
        - screener
        - (s|S)ample
        - Featurettes
        - Interview
    filesystem:
      path: "{? torrent.torrent_movie_path ?}"
      recursive: true
      regexp: '.*\.(avi|mkv|mp4)$'
      retrieve: files
    accept_all: true
    trakt_lookup: true
    template:
      - notification
    if:
      - trakt_movie_name == None: reject
    set:
      notification_message: "✅: {{ trakt_movie_name }} ({{ trakt_movie_year }})"
    move:
      to: "{? torrent.movie_path ?}/{{ trakt_movie_name }} ({{ trakt_movie_year }})"
      rename: '{{ trakt_movie_name }} ({{ trakt_movie_year }})'

  delete-transmission:
    priority: 4
    from_transmission:
      only_complete: true
      host: "{? transmission.ip ?}"
      port: 9091
      username: "{? transmission.username ?}"
      password: "{? transmission.password ?}"
    disable: [seen, seen_info_hash]
    if:
      - transmission_progress == 100: accept
      - not transmission_seed_ratio_ok: reject
      - not transmission_idle_limit_ok: reject
    transmission:
      action: remove
      host: "{? transmission.ip ?}"
      port: 9091
      username: "{? transmission.username ?}"
      password: "{? transmission.password ?}"

  # Jellyfin has issues with encoded subtitles
  # Let's extract only the relevant subtitles with ffmpeg
  extract-subtitles:
    priority: 5
    filesystem:
      path:
        - "{? torrent.tv_path ?}"
        - "{? torrent.movie_path ?}"
      recursive: true
      regexp: '.*\.(avi|mkv|mp4)$'
      retrieve: files
    accept_all: true
    seen: local
    exec:
      on_output:
        for_accepted:
          - bash "{? media.extract_subtitles_path ?}" "{{location}}"

schedules:
  - tasks: '*'
    interval:
      hours: 1
