---
- name: Converge
  hosts: all
  roles:
    - role: ../../roles/syncthing
      tags: syncthing
    - role: ../../roles/torrent
      tags: torrent
    - role: ../../roles/jellyfin
      tags: jellyfin
    - role: ../../roles/mount
      tags: mount

  vars:
    syncthing_http_user: "SyncthingUser"
    syncthing_http_password: "SyncthingPassword"

    # Send a test token
    torrent_telegram_token: "{{ lookup('env', 'TELEGRAM_TOKEN') | default('TelegramToken') }}"
    torrent_telegram_groups: "123456"
    torrent_telegram_omdb_token: "OmdbToken"

    torrent_transmission_user: "TransmissionUser"
    torrent_transmission_password: "TransmissionPassword"

    torrent_cage_non_enforcing: false

    torrent_flexget_rss: "https://rss.com"
    torrent_flexget_telegram_receiver: "Torrents"

    jellyfin_user: "jellyfintest"

    mount_paths:
      - mount_path: /mnt/dir1
        mount_from: /tmp/dir1
        type: None
        options: bind
      - mount_path: /mnt/dir2
        mount_from: /mnt/dir1/dir2
        depends: /mnt/dir1
        type: None
        options: bind
        user: mount
