---
- name: Converge
  hosts: all
  roles:
    - role: ../../roles/duckdns
      tags: duckdns
    - role: ../../roles/syncthing
      tags: syncthing
    - role: ../../roles/torrent
      tags: torrent
    - role: ../../roles/emby
      tags: emby
    - role: ../../roles/mount
      tags: mount

  vars:
    duckdns_hostname: "DuckdnsHost"
    duckdns_token: "DuckdnsToken"

    syncthing_http_user: "SyncthingUser"
    syncthing_http_password: "SyncthingPassword"

    # Send a test token
    torrent_telegram_token: "{{ lookup('env', 'TELEGRAM_TOKEN') | default('TelegramToken') }}"
    torrent_telegram_groups: "123456"
    torrent_telegram_omdb_token: "OmdbToken"

    torrent_nordvpn_user: 'NordvpnUser'
    torrent_nordvpn_password: 'NorvpnPassword'

    torrent_transmission_user: 'TransmissionUser'
    torrent_transmission_password: 'TransmissionPassword'

    torrent_flexget_rss: 'https://rss.com'
    torrent_flexget_telegram_receiver: 'Torrents'

    mount_paths:
      - mount_path: /mnt/dir1
        mount_from: /tmp/dir1
        type: None
        options: bind
      - mount_path: /mnt/dir2
        mount_from: /mnt/dir1/dir2
        depends: /mnt/dir1
        type: None
        options: bind
        user: mount
