---
- name: prepare
  hosts: all
  roles:
    - ../../roles/boilerplate
    - ../../roles/duckdns
    - ../../roles/syncthing
    - ../../roles/torrent

  vars:
   duckdns_hostname: "DuckdnsHost"
   duckdns_token: "DuckdnsToken"

   syncthing_http_user: 'SyncthingUser'
   syncthing_http_password: 'SyncthingPassword'
