---
- name: prepare
  hosts: all
  roles:
    - ../../roles/boilerplate
    - ../../roles/duckdns
    - ../../roles/syncthing
    - ../../roles/torrent

  vars:
    duckdns_hostname: "DuckdnsHost"
    duckdns_token: "DuckdnsToken"

    syncthing_http_user: "SyncthingUser"
    syncthing_http_password: "SyncthingPassword"

    # Send a test token
    torrent_telegram_token: "{{ lookup('env', 'TELEGRAM_TOKEN') | default('TelegramToken') }}"
    torrent_telegram_groups: "123456"
    torrent_telegram_omdb_token: "OmdbToken"

    torrent_nordvpn_user: 'NordvpnUser'
    torrent_nordvpn_password: 'NorvpnPassword'

    torrent_transmission_user: 'TransmissionUser'
    torrent_transmission_password: 'TransmissionPassword'

    torrent_flexget_rss: 'https://rss.com'
    torrent_flexget_telegram_receiver: 'Torrents'
