---
- name: prepare
  hosts: all
  roles:
    - ../../roles/boilerplate
    - ../../roles/duckdns
    - ../../roles/syncthing
    - ../../roles/torrent

  vars:
    deploy_user_password: 'DeployPassword'

    duckdns_hostname: "DuckdnsHost"
    duckdns_token: "DuckdnsToken"

    syncthing_http_user: "SyncthingUser"
    syncthing_http_password: "SyncthingPassword"

    torrent_telegram_token: "TelegramToken"
    torrent_telegram_groups: "1,2"

    torrent_nordvpn_user: 'NordvpnUser'
    torrent_nordvpn_password: 'NorvpnPassword'

    torrent_transmission_user: 'TransmissionUser'
    torrent_transmission_password: 'TransmissionPassword'

    torrent_jackett_user: 'JackettUser'
    torrent_jackett_password: 'JackettPassword'

    torrent_flexget_rss: 'https://rss.com'
