---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: local
    image: debian:buster
    tmpfs:
      - /tmp
      - /run
    privileged: True
    port_bindings:
      - 9092: 9092
      - 9118: 9118
    published_ports:
      # nginx Transmission
      - 0.0.0.0:9092:9092/TCP
      # nginx Jackett
      - 0.0.0.0:9118:9118/TCP
      # syncthing
      - 0.0.0.0:8384:8384/TCP
    tmpfs:
      - /tmp
      - /run
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
provisioner:
  name: ansible
  config_options:
    defaults:
      stdout_callback: yaml
      bin_ansible_callbacks: yes
verifier:
  name: ansible
