---
dependency:
  name: galaxy
driver:
  name: podman
lint: |
  set -e
  yamllint .
  ansible-lint
platforms:
  - name: local
    image: debian
    pre_build_image: false
    override_command: false
    systemd: always
    privileged: true
    published_ports:
      # nginx Transmission
      - 0.0.0.0:9092:9092/TCP
      # nginx Jackett
      - 0.0.0.0:9118:9118/TCP
      # syncthing
      - 0.0.0.0:8385:8384/TCP
      # emby
      - 0.0.0.0:8097:8096/TCP
provisioner:
  name: ansible
  config_options:
    defaults:
      stdout_callback: yaml
      bin_ansible_callbacks: true
verifier:
  name: ansible
