---
dependency:
  name: galaxy
lint: |
  set -e
  yamllint .
  ansible-lint
driver:
  name: ec2
platforms:
  - name: molecule-test
    # Debian 12 / arm
    image: ami-06dc2b03e8c5b01a8
    instance_type: t4g.micro
    region: eu-central-1
    vpc_subnet_id: subnet-024c1e52f97660217
provisioner:
  name: ansible
  config_options:
    defaults:
      stdout_callback: yaml
      bin_ansible_callbacks: true
  env:
    ANSIBLE_ROLES_PATH: ../../roles
verifier:
  name: ansible
