---
dependency:
  name: galaxy
lint: |
  set -e
  yamllint .
  ansible-lint
driver:
  name: vagrant
  provider:
    name: libvirt
platforms:
  - name: arch-test
    image: manjaro
    config_options:
      synced_folder: true
    box: generic/arch
    memory: 1024
    cpus: 1
provisioner:
  name: ansible
  config_options:
    defaults:
      stdout_callback: yaml
      bin_ansible_callbacks: true
  env:
    ANSIBLE_ROLES_PATH: ../../roles
verifier:
  name: ansible
