---
- name: Prepare tasks
  hosts: all
  become: true
  tasks:
    - name: Create mount user
      ansible.builtin.user:
        name: mount
        uid: 1200

    - name: Create directory for mount tests
      ansible.builtin.file:
        path: '/tmp/dir1/dir2'
        state: directory
        mode: '0755'

    - name: Create a file inside the mount directory
      ansible.builtin.file:
        path: '/tmp/dir1/dir2/file'
        mode: '0644'
        state: touch

    - name: Create jellyfin user
      ansible.builtin.user:
        name: jellyfintest
        uid: 1300

    - name: Create server wireguard keys directory
      ansible.builtin.file:
        path: '/tmp/wireguard/server'
        state: directory
        mode: '0755'

    - name: Create peer wireguard keys directory
      ansible.builtin.file:
        path: '/tmp/wireguard/peer1'
        state: directory
        mode: '0755'

    - name: Save private key server
      ansible.builtin.copy:
        content: "{{ torrent_custom_vpn_server_private_key }}"
        dest: /tmp/wireguard/server/privatekey-server

    - name: Save public key server
      ansible.builtin.copy:
        content: "{{ torrent_custom_vpn_server_public_key }}"
        dest: /tmp/wireguard/server/publickey-server

    - name: Save private key peer
      ansible.builtin.copy:
        content: "{{ torrent_custom_vpn_client_private_key }}"
        dest: /tmp/wireguard/peer1/privatekey-peer1

    - name: Save public key peer
      ansible.builtin.copy:
        content: "{{ torrent_custom_vpn_client_public_key }}"
        dest: /tmp/wireguard/peer1/publickey-peer1
