---
- name: Prepare tasks
  hosts: all
  become: true
  tasks:
    - name: Create mount user
      ansible.builtin.user:
        name: mount
        uid: 1200

    - name: Create directory for mount tests
      ansible.builtin.file:
        path: '/tmp/dir1/dir2'
        state: directory
        mode: '0755'

    - name: Create a file inside the mount directory
      ansible.builtin.file:
        path: '/tmp/dir1/dir2/file'
        mode: '0644'
        state: touch

    - name: Add fake entries to /etc/hosts
      lineinfile:
        dest: /etc/hosts
        line: "{{ item }}"
      with_items:
        - "127.0.0.1 syncthing.example.com"
        - "127.0.0.1 torrents.example.com"
        - "127.0.0.1 jackett.example.com"

    - name: Create directory for local backups with restic
      ansible.builtin.file:
        # Sync with restic_repository_prefix value from converge.yml
        path: "/srv/backup"
        state: directory
        mode: '0755'
