---
- name: Prepare tasks
  hosts: all
  tasks:
    - name: "Create directory"
      file:
        path: '/tmp/dir1/dir2'
        state: directory
        mode: '0755'

    - name: "Create a file inside directory"
      file:
        path: '/tmp/dir1/dir2/file'
        mode: '0644'
        state: touch
