---
## Secrets
grafana_admin_password: admin

## Non-secret variables
observability_user: observability

# Docker tag for Prometheus
observability_prometheus_version: v3.0.0-beta.0
observability_grafana_version: 11.2.0

# Tailscale integration, see your metrics through the Tailscale network
#observability_tailscale_tag: "observability"
observability_tailscale_enabled: true
observability_tailscale_hostname: observability

observability_enable_adguard_exporter: false
observability_adguard_url: "http://172.17.0.1:8080"
observability_adguard_username: "admin"
observability_adguard_password: "secret"

observability_photoprism_monitoring_enabled: false
observability_photoprism_client_id: "photoprism"
observability_photoprism_client_secret: "secret"
observability_photoprism_host: "1"
