---
- name: Install packages
  community.general.pacman:
    name:
      - python
      - python-pip
      - podman
      - htop
      - python-setuptools
      # podman-compose is unmaitained
      - docker-compose
      # Using docker for some stuff
      - docker
    update_cache: true
    state: present

- name: Enable docker service
  ansible.builtin.systemd:
    name: docker
    enabled: true
    state: started

- name: Allow binding ports lower than 1024
  ansible.posix.sysctl:
    name: net.ipv4.ip_unprivileged_port_start
    value: '80'
    sysctl_set: true
    sysctl_file: /etc/sysctl.d/10-unprivileged-port.conf
