---
- include_tasks: setup-debian.yml
  when: ansible_os_family == 'Debian'

- include_tasks: setup-arch.yml
  when: ansible_os_family == 'Archlinux'

- name: Enable docker service
  ansible.builtin.systemd:
    name: docker
    enabled: true
    state: started

- name: Allow binding ports lower than 1024
  ansible.posix.sysctl:
    name: net.ipv4.ip_unprivileged_port_start
    value: '80'
    sysctl_set: true
    sysctl_file: /etc/sysctl.d/10-unprivileged-port.conf

- name: Configure firewall (Debian/Ubuntu)
  include_tasks: setup-firewall.yml
  when: ansible_os_family == 'Debian'

- name: Disable systemd-resolved for DNS server deployment (AdGuard/Pi-hole)
  include_tasks: disable-systemd-resolved.yml
  when:
    - boilerplate_disable_systemd_resolved | default(false)
    - ansible_os_family == 'Debian'
