- name: Create deployer user
  user:
    name: deploy
    password: "{{ 'vixi' | password_hash('sha512') }}"
    update_password: on_create
    state: present
    groups: sudo

- name: Install packages
  apt:
    update_cache: yes
    name:
      - python3
      - python3-pip
      - sudo
      - htop
      - acl

# TODO: delete pi user
