- name: Create deployer user
  user:
    name: deploy
    password: "{{ 'vixi' | password_hash('sha512') }}"
    update_password: on_create
    state: present
    groups: wheel

- name: Install packages
  pacman:
    update_cache: yes
    name:
      - python
      - python-pip
      - sudo
      - htop

- name: Allow 'wheel' group to have passwordless sudo
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: '^%wheel'
    line: '%wheel ALL=(ALL) NOPASSWD: ALL'
    validate: 'visudo -cf %s'
# TODO: delete alarm user
