---
# Following instructions from https://apt.syncthing.net/
- name: Install https transport for apt
  ansible.builtin.apt:
    name: apt-transport-https
    force: true

- name: Pin syncthing repo
  ansible.builtin.copy:
    dest: /etc/apt/preferences.d/syncthing
    content: |
        Package: *
        Pin: origin apt.syncthing.net
        Pin-Priority: 990
    mode: '0644'

- name: Import Syncthing GPG key to apt
  ansible.builtin.apt_key:
    url: 'https://syncthing.net/release-key.gpg'
    state: present
    keyring: /usr/share/keyrings/syncthing-archive-keyring.gpg

- name: Add Syncthing repository
  ansible.builtin.apt_repository:
    repo: deb [signed-by=/usr/share/keyrings/syncthing-archive-keyring.gpg] https://apt.syncthing.net/ syncthing stable
    state: present

- name: Install Syncthing from Syncthing repository
  ansible.builtin.apt:
    update_cache: true
    name: syncthing
    # Latest version looks good because syncthing is very stable
    state: latest  # noqa package-latest
  notify: Restart syncthing
