---
- name: Include compose role
  ansible.builtin.include_role:
    name: compose
  vars:
    service_name: syncthing
    backup:
      enabled: true
      directories:
        - /home/syncthing/config
      schedule: "0 4 * * *"
    tailscale:
      enabled: "{{ syncthing_tailscale_enabled }}"
      hostname: "{{ syncthing_tailscale_hostname }}"
      tag: "{{ syncthing_tailscale_tag }}"
      mounts:
        - /home/syncthing/config:/syncthing_data
