---
- name: Add caddy ingress
  ansible.builtin.include_role:
    name: compose
  vars:
    service_name: syncthing
    user: syncthing

- name: Add caddy ingress
  ansible.builtin.include_role:
    name: caddy
    tasks_from: subdomains
  vars:
    subdomain_name: syncthing
    subdomain_host: 127.0.0.1
    subdomain_port: 8384
    state: present
    auth_user: "{{ syncthing_http_user }}"
    auth_password: "{{ syncthing_http_password }}"
    send_host_header: true
