---
- name: Create syncthing user
  ansible.builtin.user:
    name: syncthing

# Following instructions from https://apt.syncthing.net/ to get latest version
- name: Include syncthing installation
  ansible.builtin.include_tasks: install.yml
  tags: syncthing-install

- name: Enable syncthing service
  ansible.builtin.systemd:
    name: "syncthing@syncthing"
    enabled: true
    state: started

- name: Install caddy
  ansible.builtin.import_role:
    name: roles/caddy
    tasks_from: subdomains
  vars:
    subdomain_name: syncthing
    subdomain_host: 127.0.0.1
    subdomain_port: 8384
    state: present
    auth_user: "{{ syncthing_http_user }}"
    auth_password: "{{ syncthing_http_password }}"
