---
- name: Include compose role
  ansible.builtin.include_role:
    name: compose
  vars:
    service_name: syncthing
    user: syncthing
    tailscale:
      enabled: "{{ syncthing_tailscale_enabled }}"
      hostname: "{{ syncthing_tailscale_hostname }}"
      tag: "{{ syncthing_tailscale_tag }}"
      mounts:
        - /home/syncthing/data:/syncthing_data

- name: Run backup role
  ansible.builtin.include_role:
    name: restic
    tasks_from: backup
  vars:
    restic_backup_name: syncthing
    restic_backup_args: "/home/syncthing/data"
    restic_forget_args: "--keep-last 7"
    restic_schedule: "*-*-* 4:00:00"
