- name: Create syncthing user
  user:
    name: syncthing

- name: Install syncthing binary
  pacman:
    update_cache: yes
    name: syncthing

- name: Enable syncthing service
  systemd:
    name: syncthing@syncthing
    enabled: yes
    state: started

# based on https://github.com/le9i0nx/ansible-syncthing/blob/master/tasks/config.yml
# folder and devices management needs to be done manually via the browser
- name: get api key
  shell: grep apikey /home/syncthing/.config/syncthing/config.xml | sed -n 's:.*<apikey>\(.*\)</apikey>.*:\1:p'
  register: syncthing_apikey_raw

- name: set syncthing_apikey
  set_fact:
    syncthing_apikey: "{{ syncthing_apikey_raw.stdout }}"

- name: set https gui
  lineinfile:
    dest: /home/syncthing/.config/syncthing/config.xml
    state: present
    regexp: 'tls="false"'
    line: '<gui enabled="true" tls="true" debugging="false">'
    backrefs: yes
  notify: restart syncthing

- name: get system config
  uri:
    url: "https://localhost:8384/rest/system/config"
    return_content: yes
    validate_certs: no
    headers:
      X-API-Key: "{{ syncthing_apikey }}"
  register: syncthing_config_raw
  check_mode: no

- name: set syncthing_(config,config_old,myID)
  set_fact:
    syncthing_config: "{{ syncthing_config_raw.content | from_json }}"

- name: merge sycnthing values
  set_fact:
    syncthing_new_config: "{{ syncthing_config | combine(config_values, recursive=true) }}"
  vars:
    config_values:
      gui:
        # TODO: Appropriate pass and user from ansible-vault
        user: 'guigui'
        password: "{{ 'vixi' | password_hash('bcrypt') }}"
        useTLS: true
        address: '0.0.0.0:8384'

- name: post config
  uri:
    url: "https://localhost:8384/rest/system/config"
    method: POST
    validate_certs: no
    return_content: yes
    headers:
      X-API-Key: "{{ syncthing_apikey }}"
    body: "{{ syncthing_new_config | to_json }}"
    body_format: "json"
  when: syncthing_new_config != syncthing_config
  # notify: restart syncthing
