---
- name: Create syncthing user
  ansible.builtin.user:
    name: syncthing

# Following instructions from https://apt.syncthing.net/ to get latest version
- name: Include syncthing installation
  ansible.builtin.include_tasks: install.yml
  tags: syncthing-install

- name: Enable syncthing service
  ansible.builtin.systemd:
    name: "syncthing@syncthing"
    enabled: true
    state: started
