---
- name: Create syncthing user
  user:
    name: syncthing

# Following instructions from https://apt.syncthing.net/ to get latest version
- name: Include syncthing installation
  include: install.yml
  tags: syncthing-install

- name: Enable syncthing service
  systemd:
    name: "syncthing@syncthing"
    enabled: true
    state: started

- name: Include syncthing installation
  include: setup.yml
  tags: syncthing-setup
