---
- name: Wait for config file to be created
  ansible.builtin.wait_for:
    path: /home/syncthing/.config/syncthing/config.xml

# based on https://github.com/le9i0nx/ansible-syncthing/blob/master/tasks/config.yml
# folder and devices management needs to be done manually via the browser
- name: Get api key
  ansible.builtin.shell: |
    set -o pipefail
    grep apikey /home/syncthing/.config/syncthing/config.xml | sed -n 's:.*<apikey>\(.*\)</apikey>.*:\1:p'
  register: syncthing_apikey_raw
  changed_when: false
  args:
    executable: /bin/bash

- name: Set syncthing_apikey
  ansible.builtin.set_fact:
    syncthing_apikey: "{{ syncthing_apikey_raw.stdout }}"

- name: Set gui access through https
  ansible.builtin.lineinfile:
    dest: /home/syncthing/.config/syncthing/config.xml
    state: present
    regexp: 'tls="false"'
    line: '<gui enabled="true" tls="true" debugging="false">'
    backrefs: true
  notify: Restart syncthing

- name: Get system config
  ansible.builtin.uri:
    url: "https://localhost:8384/rest/config"
    return_content: true
    validate_certs: false
    headers:
      X-API-Key: "{{ syncthing_apikey }}"
  register: syncthing_config_raw
  check_mode: false

- name: Set syncthing_config
  ansible.builtin.set_fact:
    syncthing_config: "{{ syncthing_config_raw.content | from_json }}"

- name: Merge syncthing values
  ansible.builtin.set_fact:
    syncthing_new_config: "{{ syncthing_config | combine(config_values, recursive=True) }}"
  vars:
    config_values:
      gui:
        user: "{{ syncthing_http_user | default('admin') }}"
        password: "{{ syncthing_http_password | default('admin') }}"
        useTLS: true
        address: "0.0.0.0:8384"

- name: Update new configuration
  ansible.builtin.uri:
    url: "https://localhost:8384/rest/config"
    method: PUT
    validate_certs: false
    headers:
      X-API-Key: "{{ syncthing_config.gui.apiKey }}"
    body: "{{ syncthing_new_config }}"
    body_format: "json"
  register: response
  failed_when: response.status != 200
