---
torrent_user_gid_owner: "1500"

torrent_transmission_username: 'admin'
torrent_transmission_password: 'admin'

torrent_tailscale_enabled: true
torrent_tailscale_hostname: "torrent"
torrent_tailscale_tag: "tag:torrent"
torrent_tailscale_exit_node: true

torrent_enable_sonaar: false
torrent_enable_radarr: false
torrent_enable_kavita: false

sonarr_version: 4.0.9
radarr_version: 5.15.1
kavita_version: 0.8.4
jackkett_version: 0.22.1009
transmission_version: 4.0.6
