---
- hosts: rpis
  become: true
  vars_files:
    - secrets.yml
    - vars.yml
  tasks:
    - name: Copy rule files
      include_tasks: prom_rules/tasks/main.yml
  roles:
    - role: boilerplate
      tags: boilerplate
    - role: mount
      tags: mount
    - role: observability
      tags: observability
    - role: restic
      tags: restic
    - role: syncthing
      tags: syncthing
    - role: torrent
      tags: torrent
    - role: emby
      tags: emby
    - role: paperless
      tags: paperless
    - role: actual
      tags: actual
    # Leaving this for last, since it depends on folders and files created by other roles
    - role: share
      tags: share
