---
- include_tasks: prereq-arch.yml
  when: ansible_os_family == 'Archlinux'

- include_tasks: prereq-debian.yml
  when: ansible_os_family == 'Debian'

- name: Create user for observability
  ansible.builtin.user:
    name: "{{ observability_user }}"
    state: present
    create_home: yes
    shell: /bin/bash

- name: Create Prometheus data directory
  ansible.builtin.file:
    path: "/home/{{ observability_user }}/prometheus/data"
    state: directory
    owner: "{{ observability_user }}"
    group: "0"
    mode: '0777'

- name: Create Prometheus config directory
  ansible.builtin.file:
    path: /home/{{ observability_user }}/prometheus/config
    state: directory
    owner: "{{ observability_user }}"
    group: "0"
    mode: '0775'

- name: Create Prometheus rules directory
  ansible.builtin.file:
    path: /home/{{ observability_user }}/prometheus/config/rules
    state: directory
    owner: "{{ observability_user }}"
    group: "0"
    mode: '0775'

- name: Create Grafana data directory
  ansible.builtin.file:
    path: "/home/{{ observability_user }}/grafana/data"
    state: directory
    owner: "{{ observability_user }}"
    group: "0"
    mode: '0777'

- name: Create Alertmanager data directory
  ansible.builtin.file:
    path: "/home/{{ observability_user }}/alertmanager/data"
    state: directory
    owner: "{{ observability_user }}"
    group: "0"
    mode: '0777'

- name: Create Alertmanager config directory
  ansible.builtin.file:
    path: /home/{{ observability_user }}/alertmanager/config
    state: directory
    owner: "{{ observability_user }}"
    group: "0"
    mode: '0777'

- name: Create Alertmanager templates directory
  ansible.builtin.file:
    path: /home/{{ observability_user }}/alertmanager/config/templates
    state: directory
    owner: "{{ observability_user }}"
    group: "0"
    mode: '0777'

- name: Get docker host IP address
  ansible.builtin.shell: ip -4 addr show docker0 | grep -Po 'inet \K[\d.]+'
  register: docker_bridge_ip

- name: Set fact for docker0 IP address
  ansible.builtin.set_fact:
    docker_host_ip: "{{ docker_bridge_ip.stdout }}"

- name: Create and template prometheus.yml
  ansible.builtin.template:
    src: prometheus.yml.j2
    dest: /home/{{ observability_user }}/prometheus/config/prometheus.yml
    owner: "{{ observability_user }}"
    group: "0"
    mode: '0744'

- name: Create and template alertmanager.yml
  ansible.builtin.template:
    src: alertmanager.yml.j2
    dest: /home/{{ observability_user }}/alertmanager/config/alertmanager.yml
    owner: "{{ observability_user }}"
    group: "0"
    mode: '0744'

- name: Copy telegram template for alert manager
  ansible.builtin.copy:
    src: telegram.tmpl
    dest: /home/{{ observability_user }}/alertmanager/config/templates/telegram.tmpl
    owner: "{{ observability_user }}"
    group: "0"
    mode: '0744'

- name: Add observability user to docker group
  ansible.builtin.user:
    name: observability
    groups: docker
    append: yes

- name: Set ports for tailscale configuration
  ansible.builtin.set_fact:
    tailscale_ports:
      - 9090:9090  # Prometheus
      - 3000:3000  # Grafana

- name: Add smartctl exporter port when HDD monitoring is enabled
  ansible.builtin.set_fact:
    tailscale_ports: "{{ tailscale_ports + [observability_smartctl_exporter_port | string + ':' + observability_smartctl_exporter_port | string] }}"
  when: observability_enable_hdd_monitoring

- name: Include compose role for observability
  ansible.builtin.include_role:
    name: compose
  vars:
    service_name: observability
    user: "{{ observability_user }}"
    tailscale:
      enabled: "{{ observability_tailscale_enabled }}"
      hostname: "{{ observability_tailscale_hostname }}"
      tag: "{{ observability_tailscale_tag }}"
      ports: "{{ tailscale_ports }}"

- name: Run backup role
  ansible.builtin.include_role:
    name: restic
    tasks_from: backup
  vars:
    restic_backup_name: observability
    restic_backup_args: "/home/{{ observability_user }}/prometheus /home/{{ observability_user }}/grafana /home/{{ observability_user }}/alertmanager"
    restic_forget_args: "--keep-last 2"
    restic_schedule: "*-*-* 5:00:00"
