---
- include_tasks: prereq-arch.yml
  when: ansible_os_family == 'Archlinux'

- include_tasks: prereq-debian.yml
  when: ansible_os_family == 'Debian'

- name: Create user for observability
  ansible.builtin.user:
    name: "{{ observability_user }}"
    state: present
    create_home: yes
    shell: /bin/bash

- name: Create Prometheus data directory
  ansible.builtin.file:
    path: "/home/{{ observability_user }}/prometheus/data"
    state: directory
    owner: "{{ observability_user }}"
    group: "0"
    mode: '0777'

- name: Create Prometheus config directory
  ansible.builtin.file:
    path: /home/{{ observability_user }}/prometheus/config
    state: directory
    owner: "{{ observability_user }}"
    group: "0"
    mode: '0775'

- name: Create Grafana data directory
  ansible.builtin.file:
    path: "/home/{{ observability_user }}/grafana/data"
    state: directory
    owner: "{{ observability_user }}"
    group: "0"
    mode: '0777'

- name: Get docker host IP address
  ansible.builtin.shell: ip -4 addr show docker0 | grep -Po 'inet \K[\d.]+'
  register: docker_bridge_ip

- name: Set fact for docker0 IP address
  ansible.builtin.set_fact:
    docker_host_ip: "{{ docker_bridge_ip.stdout }}"

- name: Create and template prometheus.yml
  ansible.builtin.template:
    src: prometheus.yml.j2
    dest: /home/{{ observability_user }}/prometheus/config/prometheus.yml
    owner: "{{ observability_user }}"
    group: "0"
    mode: '0744'

- name: Add observability user to docker group
  ansible.builtin.user:
    name: observability
    groups: docker
    append: yes

- name: Check if /etc/docker/daemon.json exists
  ansible.builtin.stat:
    path: /etc/docker/daemon.json
  register: daemon_json

- name: Create /etc/docker directory if it does not exist
  ansible.builtin.file:
    path: /etc/docker
    state: directory
    mode: '0755'
  when: not daemon_json.stat.exists

- name: Create /etc/docker/daemon.json with content if it does not exist
  ansible.builtin.copy:
    dest: /etc/docker/daemon.json
    content: |
      {
        "metrics-addr": "0.0.0.0:9323"
      }
    mode: '0644'
  when: not daemon_json.stat.exists
  register: daemon_json_result

- name: Include compose role for observability
  ansible.builtin.include_role:
    name: compose
  vars:
    service_name: observability
    user: "{{ observability_user }}"
    tailscale:
      enabled: "{{ observability_tailscale_enabled }}"
      hostname: "{{ observability_tailscale_hostname }}"
      tag: "{{ observability_tailscale_tag }}"
      ports:
        # Prometheus
        - 9090:9090
        # Grafana
        - 3000:3000

- name: Restart docker service
  when: daemon_json_result.changed
  ansible.builtin.systemd:
    name: docker
    state: restarted
    enabled: true
