---
# install prometheus-node-exporter, jq, curl from pacman
- name: Install prerequisites
  community.general.pacman:
    name:
      - prometheus-node-exporter
      - jq
      - curl
      - smartmontools
    update_cache: true
    state: present
  tags: prereq
