---
# Ispired by:
# https://github.com/damex/ansible-collections-systemd/blob/21ec44d2fba75d2a299d4fea2c12bd0091c46026/.github/workflows/galaxy.yml
name: Publish to Ansible Galaxy
on: # yamllint disable-line rule:truthy
  push:
    tags:
      - v*

jobs:
  ansible-galaxy:
    name: "ansible-galaxy"
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v2"
      - uses: "actions/setup-python@v2"
      - name: Install ansible
        run: |
          pip install ansible
      - name: Build collection
        run: |
          ansible-galaxy collection build
      - name: Publish to galaxy
      - run: |
          ansible-galaxy collection publish --api-key ${{ secrets.GALAXY_API_KEY }} damex-systemd-*.tar.gz
